### ISSUE TITLE
How to define FleX_ROOT?

### ISSUE THREAD

**Issue by alantrrs** [henryclever/FleX_PyBind11#1]
Hi, I'm doing a Dockerfile for this (happy to make a PR if you're interested),  but I'm running into an issue when compiling. Seems like ``FindFlex.cmake`` is not finding the ``FleX_PATH`` since it's not reading the ``FleX_ROOT`` hint [here](https://github.com/henryclever/FleX_PyBind11/blob/master/bindings/cmake/FindFleX.cmake#L22). 
It works fine if I just hardcode the path, but I'm wondering how are you passing it when compliling via ``pip install ./bindings``?

**Comment by henryclever** [comment]
Hello,

I hard coded this in my CMakeLists.txt file. It's on line 6:


```
if (NOT DEFINED FleX_ROOT)
    set(FleX_ROOT ~/git/FleX_PyBind11)
endif()
```

If your root FleX path is somewhere else or your FleX folder is name something else (which it probably is), just edit that line accordingly in CMakeLists.txt. I suppose I could have made some auto-finder function, but I haven't gotten around to it.

Pardon my stupidity, but what is a PR? (background in Mech E., not CS, so I have knowledge gaps!) But that seems like something I'd be interested in.

-Henry C.

**Comment by alantrrs** [comment]
ah, got it. thanks! 

By PR I meant pull-request, just some GitHub lingo :). I'll submit it in a bit.

**Comment by alantrrs** [comment]
PR submitted here: https://github.com/henryclever/FleX_PyBind11/pull/2
